### ISSUE TITLE
Missing Games (all of them)

### ISSUE THREAD

**Issue by Primajin** [tauqua/gog-galaxy-itch.io#11]
I recently bought a [huge game bundle with 1704 games](https://itch.io/b/520/bundle-for-racial-justice-and-equality) but not a single one is showing up in GOG Galaxy 2. I tried it several times with 0.0.2 and 0.0.3 - also with unlinking after restart etc. Could it be that the Plugin can't handle games inside bundles?

Best

**Comment by Primajin** [comment]
So I saw there is a way to set up a private collection so that a game also shows up under purchases, not only under bundles.
Maybe this plugin could loop through each bundle and auto add every game inside to a private collection with the name of the bundle - that way they would show up individually under purchases and then might be scraped like every other purchase.

**Comment by Primajin** [comment]
OK ditch that, it's actually not about adding it to a collection but clicking on download once. So the plugin would need to loop through the bundle and simulate clicking on the download buttons once. One does not need to start the download just to go the the download page:

Before: <br>
<img width="1440" alt="Screenshot 2020-06-15 at 11 32 53" src="https://user-images.githubusercontent.com/1742115/84641904-08273400-aefc-11ea-87ae-f392cbf95931.png">

Click on download here inside the bundle: <br>
<img width="949" alt="Screenshot 2020-06-15 at 11 33 07" src="https://user-images.githubusercontent.com/1742115/84641929-12e1c900-aefc-11ea-82f5-57ab39fd98c0.png">

After: <br>
<img width="1439" alt="Screenshot 2020-06-15 at 11 33 19" src="https://user-images.githubusercontent.com/1742115/84641947-183f1380-aefc-11ea-85ee-d1ddcaa8c8fe.png">

**Comment by stellartux** [comment]
This isn't a problem with the integration plug-in. Itch has deliberately prevented games from that bundle from appearing in the library to prevent the library from being flooded. Games need to be individually claimed from the bundle to appear in your library. See the note on the bundle page.

> Note: Projects in this bundle are hidden in your library by default until you first access them in order to avoid flooding your library. You can return to this page at any time to access any projects you wish to show in your library.

**Comment by Primajin** [comment]
Ohhh thanks - well then I guess I have to flood it myself 🤦
