### ISSUE TITLE
Plugin says offline, cannot fix with disconnect and reconnect 

### ISSUE THREAD

**Issue by ozzie2014** [tauqua/gog-galaxy-itch.io#12]
I have tried reconnecting and reinstalling the plugin, however it will not stop saying that it it offline.

**Comment by Danyelalejandro** [comment]
+1

**Comment by tauqua** [comment]
This is a known issue, the plugin's system for storing cookies isn't functioning properly. I am working on fixing this.

**Comment by Danyelalejandro** [comment]
no worries, thanks for your hard work. Is there is a manual workaround in the meantime? modifying or deleting any file?

**Comment by tauqua** [comment]
Nothing consistent that I'm aware of unfortunately. It seems that booting Galaxy without the plugin installed once then closing it may clear some things so it'll work the following boot, but I don't know of anything reliable.

**Comment by ozzie2014** [comment]
I tried booting GOG without and with the plugin, but it didn't fix until I restarted my computer between removing and adding the plugin. It seems to fix after restart & reboot.

**Comment by Danyelalejandro** [comment]
Guys, this has not been fixed for me yet...

**Comment by tauqua** [comment]
The plugin is still in early development and very unstable. I am working on this problem but have no guarantees on when I can solve it

**Comment by Danyelalejandro** [comment]
Thank you so much. Your efforts are greatly appreciated!

**Comment by tauqua** [comment]
Issue should be fixed in 0.0.4
