### ISSUE TITLE
[DB] Unknown Game - Democratic Socialism Simulator

### ISSUE THREAD

**Issue by paraclete-pizza** [tauqua/gog-galaxy-itch.io#13]
Game title: Democratic Socialism Simulator

Itch.io link: https://molleindustria.itch.io/democratic-socialism-simulator

IGDB page: https://www.igdb.com/games/democratic-socialism-simulator

Steam or other store link: https://store.steampowered.com/app/1261760/Democratic_Socialism_Simulator/

Itch.io ID: 571817

GOG Database lookup link: https://gamesdb.gog.com/platforms/itch/external_releases/571817
"Release with per platform id: itch_571817 not found"

**Comment by gbdrbob** [comment]
Now seems fixed after I reported missing game to GOG. No cover art in grid view though, just game name
