### ISSUE TITLE
Unable to log in using Github credentials.

### ISSUE THREAD

**Issue by BuryTomorrow12** [tauqua/gog-galaxy-itch.io#14]
Hello there.

As you might be aware, itch allows to sign in using your github account.

However, when using that option on the plugin's login prompt, after logging in I get the "welcome back" message, but the login window doesn't close and the plugin doesn't recognize my successful login. 

My only option is to close the login window (that at this point is showing me itch game news). If I do so, the plugin disconnects.

**Comment by tauqua** [comment]
Fixed with #16 
Thanks for pointing this out
