### ISSUE TITLE
Wrong linking of games

### ISSUE THREAD

**Issue by Siphalor** [tauqua/gog-galaxy-itch.io#21]
The game "The Hex" (2018; [IGDB](https://www.igdb.com/games/the-hex)) is getting mapped to "Hex" (2017; [IGDB](https://www.igdb.com/games/hex)).

Still a really cool integration, thanks for the work :)

**Comment by tauqua** [comment]
I believe this is an issue on GoG's end. You can file a report by clicking the gear icon and clicking "Report issue".
