### ISSUE TITLE
Options window: how to make it reappear?

### ISSUE THREAD

**Issue by Raton-Laveur** [tauqua/gog-galaxy-itch.io#22]
Hi, 

On first install, the extension displayed a menu window with options regarding displaying/hiding already registered keys and such. 

After first use, where is this options window? There's no "manage" option on the extension window, and Settings/Platforms/Features has no entry for this extension. 

Thanks!

**Comment by tauqua** [comment]
This extension doesn't have an options window, you might be thinking of the [Humble Bundle integration](https://github.com/UncleGoogle/galaxy-integration-humblebundle)? That's the only extension I know of that has a settings popup.
