### ISSUE TITLE
What to do after unzipping files in proper folder?

### ISSUE THREAD

**Issue by BeJiTo1984** [tauqua/gog-galaxy-itch.io#24]
Hi,

My apologies if it sounds like a very basic and stupid question, but I followed your instructions and unzip the files within the proper /installed plugins folder.

When I restart GOG Galaxy though, it does not show any itch.io account option or entry to link from.
Is there something I'm missing here?
What are the steps to proceed with after we unzip your files?

Thanks for your support!

**Comment by gbdrbob** [comment]
Click cog in top left, go to settings->integrations. 

Itch.io should be listed under community integrations. Click the connect button to link your itch account.

If it's not there check that you have extracted it to the correct folder. The files should be in a **_subfolder_** under %LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed

e.g on my system the full path to the plugin files is:
%LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed\\**itch_v0.0.5**\\

**Comment by BeJiTo1984** [comment]
Hello!

Thanks for your reply on the matter.
The set-up was correct on my side in the first place.
I tried and change the name of the subfolder to the one you have but unfortunately, it still does not show.

See screenshots for more details.
![Paramètres](https://user-images.githubusercontent.com/71559159/94367949-92f8fc80-00af-11eb-853b-a31cfe9ac9e8.jpg)
![itch_v0 0 5](https://user-images.githubusercontent.com/71559159/94367950-968c8380-00af-11eb-8a35-db9d9751ce96.jpg)

Note that I'm using GOG Galaxy v 2.0.20.39 (Beta).

Cheers!

**Comment by tauqua** [comment]
It looks like you've downloaded a zip directly of the repository. This is meant for development and doesn't have all the requirements installed in a way Galaxy can use them. Download from the [releases page](https://github.com/tauqua/gog-galaxy-itch.io/releases) and extract in the same place as you set this one up, then make sure to restart Galaxy.

**Comment by BeJiTo1984** [comment]
Hello again
Apologies for the late reply.
I downloaded v.005 from the releases page as recommended below.
Unfortunately, Galaxy tries to load for a few minutes and then displays an error message.
I had to delete the folder to start the software again.

**Comment by tauqua** [comment]
Can you send a screenshot of what's now in your folder? It should look like this: 
![image](https://user-images.githubusercontent.com/6558398/95031877-ddfdab80-067d-11eb-84ee-6999c331a82e.png)
 with a full path of `C:\Users\[username]\AppData\Local\GOG.com\Galaxy\plugins\installed\itch_2df02142-4d8a-4a4b-9b6e-c3a0bc62f93b` (I don't believe the name of the final folder matters)
