### ISSUE TITLE
Login fails when using "Sign in with GitHub"

### ISSUE THREAD

**Issue by ComputerDruid** [tauqua/gog-galaxy-itch.io#32]
When signing in to itch.io with GitHub, the sign-in proceeds to the itch homepage instead of the "authorize application" flow. And upon trying to connect again it seems that cookies are lost so the process begins again instead of re-using the sign-in.

It worked when I used an itch username/password, though.

**Comment by tauqua** [comment]
Please make sure you're running the most recent version of the plugin. This was resolved in #16 and should be in releases v0.0.4 and later.

**Comment by ComputerDruid** [comment]
This was with v0.0.5 (the only version I've ever downloaded)

**Comment by VirgileVILE** [comment]
Same here with v0.0.5

**Comment by dephunk** [comment]
Yep fails :( Damn

**Comment by neon-dev** [comment]
Works with v0.0.6
