### ISSUE TITLE
[DB] Unknown Game - Night In The Woods

### ISSUE THREAD

**Issue by cheater** [tauqua/gog-galaxy-itch.io#5]
Game title: Night In The Woods

Itch.io link: https://finji.itch.io/night-in-the-woods

IGDB page: https://www.igdb.com/games/night-in-the-woods

Steam or other store link:
https://www.gog.com/game/night_in_the_woods
https://store.steampowered.com/app/481510/Night_in_the_Woods/

Itch.io ID: 93664

GOG Database lookup link: https://gamesdb.gog.com/platforms/itch/external_releases/93664

(not found)

**Comment by JanPokorny** [comment]
Do you know what's the problem? The game seems to be added on IGDB just fine...

**Comment by cheater** [comment]
No, I do not.

**Comment by tauqua** [comment]
This is an issue with GOG's database. You can see the page for Night in the Woods (via Steam lookup) at https://gamesdb.gog.com/platforms/steam/external_releases/481510 but the Itch release isn't listed. This seems to be one of the places where GOG's database differs from IGDB.

**Comment by JanPokorny** [comment]
@tauqua I wonder if it is possible to use platform ids for another platform? Since many Itch.io games have Steam links in their profiles, it might be possible to grab Steam appids from there. That would be a partial workaround...
