### ISSUE TITLE
Show some form of identifying information about "uknown game"

### ISSUE THREAD

**Issue by vulture-boy** [tauqua/gog-galaxy-itch.io#61]
As described in the subject; it would be a lot easier to identify missing games if they had some sort of distinguishable characteristic instead of showing up as a blank entry. This is particularly important for itch.io because of how rapidly games are introduced to the platform.

**Comment by tauqua** [comment]
Unfortunately this isn't in the control of a plugin. See [this comment from a GOG employee](https://github.com/gogcom/galaxy-integrations-python-api/issues/72#issuecomment-544411546). Even when the plugin reports the correct information, on games without much data in the database Galaxy will display them as "Unknown game" despite being passed a valid title from a plugin.
