### ISSUE TITLE
Ignore itch.io items classified as non-games, option to import physical games

### ISSUE THREAD

**Issue by vulture-boy** [tauqua/gog-galaxy-itch.io#62]
Itch projects come in multiple formats. I'm not sure due to the abundance of "Unknown Game" entries I have in my library whether non-games are or are not being imported. It should probably be noted in the README that they are filtered out if that is the case. Otherwise, it'd be good to check the classification of items before importing.

I would also appreciate an optional feature to import physical games that you own, but I recognize that they likely wouldn't have entries on IGDB, which would make things awkward.

**Comment by tauqua** [comment]
The integration *should* be importing only items which have the `game` classification. However, Itch's API seems to be inconsistent as to whether it actually respects this filter. The intended behavior of this integration is to ignore anything classified as a non-game. We do not currently have plans to allow the importing of physical games, as that's outside the scope of GOG Galaxy as a whole.

For the "Unknown Game" situation, take a look at the more detailed description in the [FAQ](https://github.com/tauqua/gog-galaxy-itch.io#why-am-i-seeing-unknown-game-can-i-do-anything-about-it)
