### ISSUE TITLE
Latest Release not working

### ISSUE THREAD

**Issue by xsm2** [tauqua/gog-galaxy-itch.io#63]
The plugin is working, the lastest release its not, and there aren't any build instructions on the proyect. Please update the release.

As for the build instructions, it should be something like that:
> - Install Python 3
> - Run build.bat
> - Copy the \src folder to C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed and rename it to itchio

The problem it's that the .bat it's not working. I manage to build it with this command (My python version is the 3.9 windows store installation)

> python3 -m pip install  -r ./requirements/app.txt --target ./src/ --no-user

With that command the plugging works as intended

**Comment by tauqua** [comment]
I just put out the [0.0.6](https://github.com/tauqua/gog-galaxy-itch.io/releases/tag/v0.0.6) release, compiled with all the changes. 

We currently handle local building through [pyinvoke/invoke](https://github.com/pyinvoke/invoke). With the development dependencies installed, you should be able to run `inv build` to compile it yourself, and there's other utility invoke commands in `tasks.py`.
