### ISSUE TITLE
Plugin has crashed. Retry

### ISSUE THREAD

**Issue by FarFromLogic** [tauqua/gog-galaxy-itch.io#66]
on GOG boot, 
when foing into settings, 
Add games & friend, 
Connect gaming account, 
When clicking connect it connects only to have the status as Plugin has crashed. Retry, retry does nothing 
![image](https://user-images.githubusercontent.com/101509737/158061305-045b3a97-c6f2-4925-a67b-2df2a360820d.png)

**Comment by tauqua** [comment]
What version of the plugin are you using? If not on v0.0.6 (latest), try updating. If you're on the latest version, can you upload the logs?

**Comment by FarFromLogic** [comment]
using the latest version
![image](https://user-images.githubusercontent.com/101509737/158070176-ae670986-6054-4462-bd58-60dbc8e4fa44.png)
![image](https://user-images.githubusercontent.com/101509737/158070199-4f24c335-57b0-4210-94fa-febd76e6cf21.png)


![image](https://user-images.githubusercontent.com/101509737/158070152-2eead82a-2da6-40de-bb50-2d2a2b676003.png)
[GalaxyClient.log](https://github.com/tauqua/gog-galaxy-itch.io/files/8240185/GalaxyClient.log)
Logs attached

**Comment by tauqua** [comment]
Could you also attach the plugin-specific log? That will give the error trace. You can trim it, but there should be an error trace at the bottom.

**Comment by FarFromLogic** [comment]
[plugin-itch-2df02142-4d8a-4a4b-9b6e-c3a0bc62f93b.log](https://github.com/tauqua/gog-galaxy-itch.io/files/8240431/plugin-itch-2df02142-4d8a-4a4b-9b6e-c3a0bc62f93b.log)

please see attached

not sure if this would help but I am also on the windows 11 insider dev build 22572 release 220304-1536

**Comment by tauqua** [comment]
You appear to be missing some module files. including `typing_extensions`, which appears to be causing the problem. The installed folder should have 73 files as of v0.0.6, yours has 71 according to your screenshot. If you installed this using the `inv` command, this could be a Python version-specific issue (tested on 3.7 but may not work on 3.8 and above).

Regardless, your best bet would be to reinstall fresh from the releases page and double check that you've ended up with the 73 files in this release.

**Comment by FarFromLogic** [comment]
looks like the initial download was somehow incomplete, re-downloading has fixed things, 

I think the issue was with Files 3rd party file explorer not doing a full unzip of the previous download
